# Generated by Django 5.2.3 on 2025-06-27 21:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ACARSMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aircraft_id', models.CharField(help_text='Rejestracja statku powietrznego', max_length=10)),
                ('flight_number', models.CharField(help_text='Numer lotu', max_length=10)),
                ('route', models.CharField(blank=True, help_text="Trasa: np. 'WAW-JFK'", max_length=50)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, help_text='Szerokość geograficzna', max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, help_text='Długość geograficzna', max_digits=9, null=True)),
                ('altitude', models.IntegerField(blank=True, help_text='Wysokość w stopach', null=True)),
                ('speed', models.IntegerField(blank=True, help_text='Prędkość w węzłach (TAS/IAS)', null=True)),
                ('heading', models.IntegerField(blank=True, help_text='Kierunek w stopniach', null=True)),
                ('time_off', models.TimeField(blank=True, help_text='OF – Time Off (odlot z bramki)', null=True)),
                ('time_on', models.TimeField(blank=True, help_text='ON – Time On (przylot na pas)', null=True)),
                ('estimated_over', models.TimeField(blank=True, help_text='EO – Estimated Time Over', null=True)),
                ('estimated_ramp', models.TimeField(blank=True, help_text='ERT – Estimated Ramp Time', null=True)),
                ('engine_n1', models.DecimalField(blank=True, decimal_places=2, help_text='N1 – prędkość turbiny niskiego stopnia', max_digits=5, null=True)),
                ('engine_epr', models.DecimalField(blank=True, decimal_places=2, help_text='EPR – Exhaust Pressure Ratio', max_digits=5, null=True)),
                ('fuel_flow', models.DecimalField(blank=True, decimal_places=2, help_text='FF – Fuel Flow', max_digits=7, null=True)),
                ('fuel_on_board', models.DecimalField(blank=True, decimal_places=2, help_text='FOB – Fuel On Board', max_digits=8, null=True)),
                ('maintenance_code', models.CharField(blank=True, help_text='MN – kod konserwacji', max_length=10)),
                ('fault_report', models.CharField(blank=True, help_text='FLR – opis błędu/usterki', max_length=50)),
                ('temperature_oat', models.DecimalField(blank=True, decimal_places=2, help_text='OAT – Outside Air Temperature', max_digits=5, null=True)),
                ('wind_info', models.CharField(blank=True, help_text='WND – informacje o wietrze', max_length=50)),
                ('pax_count', models.IntegerField(blank=True, help_text='PAX – liczba pasażerów', null=True)),
                ('load_weight', models.DecimalField(blank=True, decimal_places=2, help_text='ZW – Zero Fuel Weight', max_digits=8, null=True)),
                ('cost_index', models.IntegerField(blank=True, help_text='CI – Cost Index', null=True)),
                ('center_of_gravity', models.DecimalField(blank=True, decimal_places=2, help_text='CG – Center of Gravity', max_digits=5, null=True)),
                ('transmission_mode', models.CharField(blank=True, help_text='Tryb transmisji (A/B etc.)', max_length=4)),
                ('label', models.CharField(blank=True, help_text='Label – dwuznakowy kod wiadomości', max_length=2)),
                ('msg_number', models.IntegerField(blank=True, help_text='Msg No. – numer sekwencji wiadomości', null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='Data i czas odbioru lub wysłania')),
                ('direction', models.CharField(choices=[('IN', 'Incoming'), ('OUT', 'Outgoing')], help_text='Kierunek komunikatu', max_length=4)),
                ('payload', models.JSONField(help_text='Pełny, surowy JSON komunikatu ACARS')),
                ('user', models.ForeignKey(help_text='Użytkownik, który odebrał lub wysłał wiadomość', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Komunikat ACARS',
                'verbose_name_plural': 'Komunikaty ACARS',
                'ordering': ['-timestamp'],
            },
        ),
    ]
