# Generated by Django 5.2.3 on 2025-06-28 13:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ACARSMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aircraft_id', models.CharField(max_length=10, verbose_name='ID Samolotu')),
                ('flight_number', models.CharField(blank=True, max_length=10, verbose_name='Numer Lotu')),
                ('route', models.CharField(blank=True, max_length=50, verbose_name='Trasa')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Szerokość geograficzna')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Długość geograficzna')),
                ('altitude', models.IntegerField(blank=True, null=True, verbose_name='Wysokość (ft)')),
                ('speed', models.IntegerField(blank=True, null=True, verbose_name='Prędkość (kts)')),
                ('heading', models.IntegerField(blank=True, null=True, verbose_name='Kurs (°)')),
                ('time_off', models.TimeField(blank=True, null=True, verbose_name='Czas startu')),
                ('time_on', models.TimeField(blank=True, null=True, verbose_name='Czas lądowania')),
                ('engine_n1', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='N1 (%)')),
                ('engine_epr', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='EPR')),
                ('fuel_flow', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Przepływ paliwa (kg/h)')),
                ('pax_count', models.IntegerField(blank=True, null=True, verbose_name='Liczba pasażerów')),
                ('cost_index', models.IntegerField(blank=True, null=True, verbose_name='Indeks kosztów')),
                ('transmission_mode', models.CharField(blank=True, max_length=4, verbose_name='Tryb transmisji')),
                ('label', models.CharField(blank=True, max_length=2, verbose_name='Etykieta wiadomości')),
                ('msg_number', models.IntegerField(blank=True, null=True, verbose_name='Numer wiadomości')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Czas otrzymania')),
                ('direction', models.CharField(choices=[('IN', 'Przychodzące'), ('OUT', 'Wychodzące')], max_length=4, verbose_name='Kierunek wiadomości')),
                ('payload', models.JSONField(verbose_name='Pełne dane JSON')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Użytkownik')),
            ],
            options={
                'verbose_name': 'Wiadomość ACARS',
                'verbose_name_plural': 'Wiadomości ACARS',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', '-timestamp'], name='acars_acars_user_id_c059ff_idx'), models.Index(fields=['aircraft_id', '-timestamp'], name='acars_acars_aircraf_5d371c_idx'), models.Index(fields=['flight_number', '-timestamp'], name='acars_acars_flight__21c821_idx')],
            },
        ),
    ]
