# Generated by Django 5.2.3 on 2025-06-27 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acars', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acarsmessage',
            name='flight_number',
            field=models.CharField(blank=True, help_text='Numer lotu', max_length=10),
        ),
    ]
