# Generated by Django 5.2.3 on 2025-06-28 15:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acars', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SmartcarsProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_key', models.CharField(max_length=64, unique=True, verbose_name='API Key SmartCARS')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data utworzenia')),
                ('last_used', models.DateTimeField(blank=True, null=True, verbose_name='Ostatnie użycie')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktywny')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Użytkownik')),
            ],
            options={
                'verbose_name': 'Profil SmartCARS',
                'verbose_name_plural': 'Profile SmartCARS',
            },
        ),
    ]
