name: Deploy Django App

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    environment: HARBOR

    steps:
      - name: Checkout source repo
        uses: actions/checkout@v3

      - name: Extract tag
        id: vars
        run: echo "TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Harbor
        run: echo "${HARBOR_PASSWORD}" | docker login harbor.zatto-lab.cloud -u "${HARBOR_USERNAME}" --password-stdin
        env:
          HARBOR_USERNAME: ${{ secrets.HARBOR_USERNAME }}
          HARBOR_PASSWORD: ${{ secrets.HARBOR_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build -t harbor.zatto-lab.cloud/d-topsky/d-topsky:${{ env.TAG }} .
          docker push harbor.zatto-lab.cloud/d-topsky/d-topsky:${{ env.TAG }} 